# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
         name: "Say my name !"
         command: "echo ${MY_NAME_VAR}"
      - run:
         name : "Create a file"
         command : echo "Hello world from output.txt" > ~/output.txt
      - persist_to_workspace:
           root: ~/
           paths: output.txt
  print_output_file: 
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Say le monde name"
          command: "echo le monde!"
      - attach_workspace:
          at: ~/
      - run: cat output.txt
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  welcome_tuto:
    jobs:
      - save_hello_world_output
      - print_output_file :
         requires: [save_hello_world_output]

